// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppDir() {
  return window['go']['main']['App']['AppDir']();
}

export function ChooseProjectDir() {
  return window['go']['main']['App']['ChooseProjectDir']();
}

export function CreateProject(arg1, arg2) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2);
}

export function DefaultProjectDir() {
  return window['go']['main']['App']['DefaultProjectDir']();
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function GetUIState() {
  return window['go']['main']['App']['GetUIState']();
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListSessions() {
  return window['go']['main']['App']['ListSessions']();
}

export function LoadProject(arg1) {
  return window['go']['main']['App']['LoadProject'](arg1);
}

export function MoveProject(arg1) {
  return window['go']['main']['App']['MoveProject'](arg1);
}

export function OpenProjectFile() {
  return window['go']['main']['App']['OpenProjectFile']();
}

export function ProjectPath(arg1) {
  return window['go']['main']['App']['ProjectPath'](arg1);
}

export function RenameProject(arg1, arg2) {
  return window['go']['main']['App']['RenameProject'](arg1, arg2);
}

export function SaveProject(arg1) {
  return window['go']['main']['App']['SaveProject'](arg1);
}

export function SaveSessions(arg1) {
  return window['go']['main']['App']['SaveSessions'](arg1);
}

export function SaveUIState(arg1) {
  return window['go']['main']['App']['SaveUIState'](arg1);
}

export function SendRequest(arg1, arg2) {
  return window['go']['main']['App']['SendRequest'](arg1, arg2);
}
