// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {store} from '../models';
import {updater} from '../models';

export function AppDir():Promise<string>;

export function AppVersion():Promise<string>;

export function CheckForUpdate():Promise<updater.Info>;

export function ChooseProjectDir():Promise<string>;

export function CreateProject(arg1:string,arg2:string):Promise<model.Project>;

export function DefaultProjectDir():Promise<string>;

export function DeleteProject(arg1:string):Promise<void>;

export function DownloadAndInstallUpdate(arg1:string,arg2:string):Promise<void>;

export function GetUIState():Promise<store.UIState>;

export function ListProjects():Promise<Array<model.ProjectSummary>>;

export function ListSessions():Promise<Array<model.Session>>;

export function LoadProject(arg1:string):Promise<model.Project>;

export function MoveProject(arg1:string):Promise<model.Project>;

export function OpenProjectFile():Promise<model.Project>;

export function ProjectPath(arg1:string):Promise<string>;

export function RenameProject(arg1:string,arg2:string):Promise<model.Project>;

export function SaveProject(arg1:model.Project):Promise<model.Project>;

export function SaveSessions(arg1:Array<model.Session>):Promise<void>;

export function SaveUIState(arg1:store.UIState):Promise<void>;

export function SendRequest(arg1:model.Request,arg2:Record<string, string>):Promise<model.Response>;
